name: Build APK
on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create App and Build APK
        run: |
          cordova create myApp com.nabil.app "MyAPP"
          cd myApp
          cordova platform add android
          rm -rf www/*
          echo '${{ github.event.client_payload.html_content }}' > www/index.html
          cordova build android --no-telemetry
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-apk
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
